---
title: "aRboretum : Modernizing botanical labels : towards an inclusive and automated scientific mediation"

# Output formats
format:
  stylisharticle-pdf:
    keep-tex: true
    # Color example, see "Text color"
    header-includes:
      \definecolor{grey}{RGB}{191, 191, 191}
  stylisharticle-html:
    # Color example, see "Text color"
    css: colors.css
# Authors (https://quarto.org/docs/journals/authors.html#author-schema)
author:
  - name: Martin Boucknooghe
    affiliations:
      - name: Université de Montpellier
        address: 30 place Eugène Bataillon
        city: Montpellier
        country: France
        postal-code: 34090
      - name: AgroParisTech
        address: 648 Rue Jean François Breton
        city: Montpellier
        country: France
        postal-code: 34090
    orcid: 0000-0000-0000-0000
    email: martin.boucknooghe@etu.umontpellier.fr
    
  - name: Domingos Cardoso
    affiliations:
      - name: Jardim Botânico do Rio de Janeiro
        address:  Rua Jardim Botânico, 1008
        city: Rio de Janeiro
        country: Brasil
        postal-code: 22470-180
    orcid: 0000-0000-0000-0000
    email: 

# Abstract and Keywords
abstract: |
  As biodiversity continues to decline at an alarming rate, raising public awareness has become a crucial seed from which individual consciousness can grow and collective action can flourish. This paper presents aRboretum, an open-source R package designed to transform botanical garden labels into effective scientific outreach tools. In response to the limitations of traditional plant labels and the urgent need for new approaches to public engagement, aRboretum automates the production, digitization, and enrichment of multilingual botanical labels. It integrates reliable taxonomic data, generates descriptions in multiple languages, and incorporates both audio and visual features. Designed as a modular tool, aRboretum streamlines label production, improves accessibility, and promotes inclusion by providing a participatory scientific communication platform adaptable to botanical gardens, education, biodiversity conservation, and many other applications.
keywords: [à remplir]
# Bibliography
reference-section-title: References
bibliography: references.bib
# Language
lang: en-GB
otherlangs: pt-BR
# Code options 
# https://quarto.org/docs/computations/execution-options.html
execute:
  # show code chunk output
  include: true
  # Show the code in the output
  echo: false
  # Show messages
  message: false
  # Show warnings
  warning: false
  # Cache code results
  cache: true
# Template specific
journalinfo: "Publication reference"
archive: "DOI: xxx/xx"
keywordlabel: Keywords
corrauthorlabel: Corresponding Author
---

```{r}
#| label: Options
### Customized R options for this document
# Delete this chunk if you don't use R

# Necessary packages. Add all packages used in the code here.
packages_required <- c(
  # R tools, do not modify
  "knitr",
  # Add specific packages here
  "divent",
  "tidyverse", 
  "vegan"
)
# Already installed?
packages_installed <- vapply(
  packages_required, 
  FUN = requireNamespace, 
  FUN.VALUE = TRUE, 
  quietly = TRUE
) 
# Install missing packages
install.packages(names(packages_installed)[!packages_installed])

# Allow size='small' or any valid Latex font size in chunk options
def.chunk.hook <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(
  chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    ifelse(
      options$size == "normalsize", 
      yes = x,
      no = paste0("\n \\", options$size, "\n\n", x, "\n\n \\normalsize")
    )
  }
)

# knitr options (https://yihui.org/knitr/options/)
knitr::opts_chunk$set(
  # Code chunk automatic format if tidy is TRUE
  tidy = TRUE, 
  # Tidy code options: remove blank lines and cut lines after 50 characters
  tidy.opts = list(blank = FALSE, width.cutoff = 50),
  # Font size in PDF output
  size = "scriptsize", 
  # Select PDF figures in PDF output if PDF file exists beside PNG file
  knitr.graphics.auto_pdf = TRUE
)
# Text width of R functions output
options(width = 50)

# ggplot style
library("tidyverse")
# Function to call in each chunk that produces a figure
ggtheme_set <- function() {
  theme_set(theme_bw())
  theme_update(
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )
}
knitr::opts_chunk$set(dev.args = list(bg = "transparent"))

# Random seed
set.seed(973)
```

# Introduction

Botanical gardens play an essential multifunctional role for ex situ conservation, environmental education and taxonomic research.
According to the International Union for Conservation of Nature (IUCN), these institutions maintain and house more than 100,000 plant species, or about 30% of the world's vascular flora with an overrepresentation of endangered species [@mounce2017].
Yet, their scientific and educational value is generally underexplored due to structural limitations in communicating information to visitors.
Indeed, botanical gardens are not content with conserving plants; They represent spaces for raising awareness for the general public.
Their mission therefore includes the transmission of knowledge, an issue that is all the more crucial as global biodiversity is in accelerated decline [@ipbes2019].

In this context, the botanical label is the first vector of information linking the public and living collections, and a key tool for mediating between science and the public.
Traditionally, it is limited to the scientific name, the local vernacular name, the family and sometimes the country of origin.
However, this approach has three major limitations that hinder scientific mediation and the enhancement of collections.
First, printed labels are frozen in time, whereas taxonomy is dynamic: progress in molecular phylogeny, the integration of new morphological data and the revision of herbarium collections lead to regular updates [@freiberg2020].
For example, Caesalpinia echinata (Fabaceae) was renamed Paubrasilia echinata in 2016 [@gagnon2016], an update that will only be reflected on JBRJ labels after a long period of time.
This obsolescence leads to misinformation among visitors and/or costly and time-consuming work.
Second, these labels are exclusionary.
Visually impaired visitors and those who cannot read, such as children, cannot access the information independently.
The language barrier also limits visitors' understanding, particularly given the very large number of international tourists that Rio de Janeiro welcomes each year, nearly 2.2 million in 2025 [@governodoestadodoriodejaneiro2025].
Finally, traditional labels are passive, whereas, according to @harada2018, interactive experiences promote visitor engagement and enhance learning by stimulating active participation.

The development of open science and citizen science encourages the provision of data and tools that are reproducible, transparent and accessible to all [@europeancommission2016].
In this context, botanical mediation tools must evolve towards open, modular and participatory platforms, allowing the integration of diverse content, including local and community knowledge.

Several tools approach these challenges, but none responds to them fully.
Expowo [@zuanny2026] and refloraR (retrouver la ref: Cardoso and Calderón 2026) allow the extraction of botanical and ecological data (POWO for the world, FFB for Brazil), but require manual processing in several steps.
labeleR [@ramos-gutierrez2026] is a tool designed for the creation of labels for herbaria; it does not manage living collections, is limited to minimal information (scientific name, family, locality), and does not integrate enriched data.
Moreover, its use requires expertise in R and it does not offer interactive features.
Thus, no existing tool offers an integrated, accessible and interactive solution for living collections.

Faced with this observation, we developed the aRboretum package to answer four major questions: (1) how can the production chain of botanical labels (from raw data to final display) be automated while guaranteeing taxonomic reliability, avoiding manual errors and reducing production time by relying on reliable sources; (2) how can heterogeneous data (FFB, POWO, local knowledge) be integrated and standardised to produce labels that are both scientifically rigorous and rich in contextual information, combining structured data (taxonomy, distribution) with additional local content (vernacular names, uses, free notes); (3) how can botanical information be made accessible to all audiences, as widely as possible, to maximize the educational and inclusive impact of botanical gardens; and (4) how can this tool be made accessible and usable by a multitude of institutions and actors, through a simple interface that can be adapted to different contexts.

Here, we introduce aRboretum, an open-source R package that allows the automatic generation of enriched and multilingual digital botanical labels for living collections, from taxonomic data from Flora e Funga do Brasil (FFB).
In the course of its development, additional features were added: integration of a global database (Plants of the World Online), enrichment of labels with audio, interactivity, and the integration of local and personal content such as photos or audio recordings.
The design of aRboretum was based on an analysis of the needs of end users, mainly visitors and staff of botanical gardens, but also of additional uses (education, personal collections, awareness-raising and participatory projects, nurseries, ecotourism).
This analysis led to a modular and scalable architecture capable of managing the extraction, cleaning, merging and visualization of botanical data, and allowing the subsequent addition of new features.
The core function of the package performs data extraction and standardization: it queries two major data sources (FFB and POWO), resolves synonyms, merges information, and produces a standardized and enriched dataset (plant uses, free notes, additional languages, new vernacular names), in order to guarantee taxonomic reliability and richness of information.
Optional media management modules allow the integration of personal photos, with automatic compression, and of audio recordings, either personal ones or the browser's text-to-speech as a fallback.
Finally, HTML label and minisite generation functions were developed using modern web solutions (HTML5, CSS3, JavaScript, Leaflet.js, Web Speech API, JSON, Base64) to enable an interactive and responsive experience.
Together, these features make aRboretum a functional, innovative, inclusive and sustainable tool, capable of adapting to the evolving needs of living botanical collections and their users.

# Methods and Results

# Conclusion

12
